/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.record.View;

import java.sql.Connection;
import medical.record.Controller.Auth;
import medical.record.Controller.Conf;
import medical.record.Controller.Service;

/**
 *
 * @author Acer
 */
public class ViewDetailPasien extends javax.swing.JFrame {

    /**
     * Creates new form ViewDetailDokter
     */
    Connection conn;
    Auth auth;
    Service fc = new Service();
    int id;
    
    public ViewDetailPasien() {
        initComponents();
    }

    ViewDetailPasien(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        conn = Conf.databaseConnected();
        auth = new Auth();
        tableRM.setModel(fc.getModelRM());
        fc.loadPasien();
    }
    
    public void setDataPasien(){
        tfIdPasien.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfIdPasien = new javax.swing.JLabel();
        tfTanggal = new javax.swing.JLabel();
        tfNama = new javax.swing.JLabel();
        tfUmur = new javax.swing.JLabel();
        tfGender = new javax.swing.JLabel();
        tfNotelp = new javax.swing.JLabel();
        tfPekerjaan = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRM = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(42, 147, 151));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/record/assets/rekam-medik-asset/arrow-back.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detail Pasien");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 30, 547, 112);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/record/assets/rekam-medik-asset/Group 27.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1014, 28, 370, 110);

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/record/assets/rekam-medik-asset/Group 41.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 859, 127, 186);

        tfIdPasien.setBackground(new java.awt.Color(255, 255, 255));
        tfIdPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfIdPasien.setForeground(new java.awt.Color(0, 0, 0));
        tfIdPasien.setText("id");
        jPanel1.add(tfIdPasien);
        tfIdPasien.setBounds(390, 200, 220, 22);

        tfTanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTanggal.setForeground(new java.awt.Color(0, 0, 0));
        tfTanggal.setText("tanggal");
        jPanel1.add(tfTanggal);
        tfTanggal.setBounds(390, 290, 210, 22);

        tfNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNama.setForeground(new java.awt.Color(0, 0, 0));
        tfNama.setText("nama");
        jPanel1.add(tfNama);
        tfNama.setBounds(390, 240, 210, 22);

        tfUmur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfUmur.setForeground(new java.awt.Color(0, 0, 0));
        tfUmur.setText("umur");
        jPanel1.add(tfUmur);
        tfUmur.setBounds(390, 330, 210, 22);

        tfGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfGender.setForeground(new java.awt.Color(0, 0, 0));
        tfGender.setText("gender");
        jPanel1.add(tfGender);
        tfGender.setBounds(920, 190, 220, 22);

        tfNotelp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNotelp.setForeground(new java.awt.Color(0, 0, 0));
        tfNotelp.setText("notelp");
        jPanel1.add(tfNotelp);
        tfNotelp.setBounds(920, 230, 210, 22);

        tfPekerjaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPekerjaan.setForeground(new java.awt.Color(0, 0, 0));
        tfPekerjaan.setText("pekerjaa");
        jPanel1.add(tfPekerjaan);
        tfPekerjaan.setBounds(920, 270, 240, 22);

        tfAlamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(0, 0, 0));
        tfAlamat.setText("Alamat ");
        tfAlamat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(tfAlamat);
        tfAlamat.setBounds(920, 310, 270, 80);

        tableRM.setBackground(new java.awt.Color(255, 255, 255));
        tableRM.setForeground(new java.awt.Color(0, 0, 0));
        tableRM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal Masuk", "Tanggal Keluar", "Jenis Rekam Medis", "Dokter Pemeriksa", "Pemeriksaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRM);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(186, 446, 1053, 389);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/record/assets/rekam-medik-asset/Group 42.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1020, 841, 420, 210);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ID Pasien        :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(240, 200, 129, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nama Pasien   :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(240, 240, 125, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Tanggal Lahir  :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(240, 290, 125, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Umur             :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(240, 330, 127, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Jenis Kelamin     :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(758, 192, 143, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nomor Telepon  :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(758, 232, 140, 22);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Pekerjaan          :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(758, 272, 142, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Alamat             :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(758, 312, 138, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 437, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        ViewDashboard menu = new ViewDashboard();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetailPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetailPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetailPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetailPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDetailPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRM;
    private javax.swing.JLabel tfAlamat;
    private javax.swing.JLabel tfGender;
    private javax.swing.JLabel tfIdPasien;
    private javax.swing.JLabel tfNama;
    private javax.swing.JLabel tfNotelp;
    private javax.swing.JLabel tfPekerjaan;
    private javax.swing.JLabel tfTanggal;
    private javax.swing.JLabel tfUmur;
    // End of variables declaration//GEN-END:variables
}
